server:
  port: 8000
spring:
  application:
    name: microservice-simple-provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true